# Generated by Django 3.0.5 on 2022-07-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hotels_emenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='hotel_link',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
